apiVersion: apps/v1
kind: Deployment
metadata:
  name: shivam-deploy
  labels:
    app: shivam-mvn-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: shivam-mvn-app
  template:
    metadata:
      labels:
        app: shivam-mvn-app
    spec:
      containers:
      - name: shivam-mvn-container
        image: shivamsaxena91/shivam-docker-demo:shivam-docker-demo
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: shivam-np-service
  labels:
    app: shivam-mvn-app
spec:
  selector:
    app: shivam-mvn-app

  type: NodePort
  ports:
  - nodePort: 31000
    port: 8080
    targetPort: 8080
